---
name: docs

on:
  push:
    branches:
      - main
    tags:
      - v*
  workflow_dispatch:

jobs:
  docs:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
      - uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0
        with:
          enable-cache: True
      - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6
      - run: uv sync --all-extras --dev
      - run: |
          git config --global user.name "$(git --no-pager log --format=format:'%an' -n 1)"
          git config --global user.email "$(git --no-pager log --format=format:'%ae' -n 1)"
          git fetch origin gh-pages:gh-pages
      - run: echo "TAG=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - run: uv run mike deploy --push ${TAG:-latest}
