# vim: ft=yaml
name: test

on:
  push:
  pull_request:
  workflow_dispatch:

env:
  PY_COLORS: "1"
  FORCE_COLOR: true
  UV_PYTHON_PREFERENCE: system

jobs:
  test:
    name: Salt ${{ matrix.salt }}
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        include:
          # TODO: Keep Python versions in sync with salts onedir distributions.
          - { python: "3.14", salt: "3008" }
          - { python: "3.11", salt: "3006" }
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7
        with:
          python-version: ${{ matrix.python }}
      - uses: astral-sh/setup-uv@bec219d24cd3e171d82865faccec33120bb574f4 # v10.1.0
        with:
          enable-cache: True
      - run: uv sync --dev
      - run: uv run nox --session 'test(salt${{ matrix.salt }})' -- -vv

  ruff-check:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - uses: astral-sh/setup-uv@bec219d24cd3e171d82865faccec33120bb574f4 # v10.1.0
        with:
          enable-cache: True
      - uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7
        with:
          python-version: "3.14"
      - run: uv sync --only-group=lint
      - run: uv run ruff check

  ruff-format:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - uses: astral-sh/setup-uv@bec219d24cd3e171d82865faccec33120bb574f4 # v10.1.0
        with:
          enable-cache: True
      - uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7
        with:
          python-version: "3.14"
      - run: uv sync --only-group=lint
      - run: uv run ruff format --diff --check
